# Aims
<!-- Aim = what you hope to achieve; Objectives the action you will take to achieve the aims --> 
The primary aim of this thesis was to relate the adaptive response to resistance training with low- and moderate-volume to skeletal-muscle characteristics in previously untrained individuals. The key question was whether manipulation of exercise volume will have different effects in different individuals and if this variability was associated with individual characteristics. A further aim was to characterize effects of exercise volume on molecular muscle characteristics and determine a time course profile of ribosomal biogenesis markers in response to resistance training. <!-- A final aim of the present thesis was to develop an implementation of unbiased reference gene selection to aid gene expression analysis in repeated measures designs   --> Based on these aims, the objectives were;

- to associate skeletal muscle and systemic characteristics to the benefit of moderate- compared to low-volume resistance training,
- to determine volume-dependence of molecular networks related to muscle growth and remodeling in response to resistance training, and,
- to determine a time course of markers related to ribosome biogenesis in the early phase of resistance training.


<!-- To create a software implementation of reference gene selection algorithms -->