# Svensk sammanfattning

Systematisk styrketräning leder till en större skelettmuskelmassa och förbättrade funktionella egenskaper hos det neuromuskulära systemet. Dessa förändringar leder till generella hälsofördelar oavsett ålder och tidigare aktivitetsnivå. Genom att variera intensitet, val av träningsövningar och volym kan styrketräning skräddarsys för att anpassas till individuella mål och utgångspunkter. På vilka indikationer sådana förändringar av träningsbelastningar ska utföras är inte klart. Styrketräningens volym, uttryckt som antal serier per muskelgrupp och träningspass eller träningsvecka har identifierats som en viktig faktor för träningsresultaten. Det är dock sannolikt att individer varierar med avseende på volymberoende i träningsresultat som muskelmassa och styrka.

Det primära syftet med denna avhandling var att relatera anpassningar till styrketräning, genomfört med låg och måttlig volym till individuella egenskaper hos otränade individer.
Vidare syftade arbetet som presenteras här till att karakterisera hur träningsvolym påverkar molekylära 
egenskaper i skelettmuskel och beskriva tidsförloppet för nybildning av ribosomer under den tidiga fasen av ett styrketräningsprogram.

I en första studie (Studie I) genomförde unga, friska, otränade manliga och kvinnliga deltagare (n = 34) en 12 veckor lång träningsintervention med 2-3 träningspass per vecka. Träningen genomfördes med en kontra-lateral träningsmodell där ett ben tränade med låg volym (en serie per övning) och det andra benet tränade med moderat volym (tre serier per övning). 
Den främre lårmuskelns tvärsnittsarea och styrka mättes före och efter träningsperioden.
Muskelprover togs från den m. vastus lateralis före och efter träningsinterventionen samt före och en timme efter det femte träningspasset.

Träningsperioden ledde till muskelhypertrofi och ökad muskelstyrka, denna ökning var volymberoende med större framgångar som svar på moderat träningsvolym. Detta sammanföll med större aktivering av molekylär signalering och högre nivåer av markörer relaterade till nybildning av ribosomer. Vidare ledde träning med moderat volym till mer utbredd övergång från muskelfibertyp IIX till IIA. Tillsammans visade detta att moderat träningsvolym ledde till mer uttalade funktionella och biologiska anpassningar än träning med låg volym.
Tretton respektive sexton deltagare identifierades ha fördel av att träna med moderat träningsvolym då dessa fick större framgång med denna metod jämfört med låg träningsvolym. Dessa individer visade sig också ha en större ackumulering av RNA i benet som tränade med den högre träningsvolymen efter fyra träningspass. Detta indikerar att förmågan att differentiera nybildning av ribosomer i den inledande fasen av en träningsperiod förutsäger långsiktiga fördelar med moderat träningsvolym.

Resultaten från studie I kombinerades med tidigare studier i en metaanalys. Denna gav stöd för att träningsvolymen generellt sett är en viktig variabel då både muskelmassa och styrka ökar mer när träning genomförs med större volym. Meta-analysen visade dock att en ökad träningsvolym inte leder till ökad muskelmassa eller styrka i överkroppen.

RNA från ett urval (n = 25) av deltagarna i Studie I användes till RNA sekvensering. Urvalet gjordes baserat på RNA-kvalité. För att etablera en ändamålsenlig analys genomfördes en systematisk utvärdering av olika bioinformatiska verktyg. Dessa utvärderades bland annat baserat på variationen inom varje forskningsdeltagare innan träning inleddes och korrelationen mellan relativa nivåer av mRNA och protein av myosin (myosin heavy-chain).
Vidare användes olika normaliseringsstrategier för att kunna jämföra de olika träningsvolymerna. Detta då volymberoende ackumulering av RNA som svar på styrketräningen ledde till att olika mängder muskelvävnad användes i analyser då en bestämd mängd RNA användes vid förberedelse av analyserna.
Analyserna visade ett ökat uttryck av gener som var relaterade till den extracellulära stödstrukturen efter två veckors träning. Inga skillnader i genuttryck identifierades efter träningsperioden när hänsyn togs till den mängd musklevävnad som användes i vid förberedelse av analyserna. Detta i motsats till resultat från normaliseringsstrategier som inte tog samma hänsyn. Här identifierades istället kontraintuitivt högre uttryck av olika gener som svar på träning med låg volym.

Givet att nybildningen av ribosomer i inledningsfasen av en träningsperiod spelar en viktig roll för de långsiktiga träningsresultaten så genonfördes ytterligare en studie med syfte att vidare undersöka denna process. Specifikt ville vi beskriva tidsförloppet för träningsinducerad ackumulering av ribosomala markörer. Vidare ville vi undersöka om variationer i träningsvolym eller ett kortare träningsavbrott skulle påverka markörer för ribosomal nybildning.

Arton deltagare deltog i studien och ingick antingen i en träningsgrupp (n = 11) eller en kontrollgrupp (n = 7). Träningsgruppen genomförde tolv träningspass där det ena benet tränade lårets framsida med en konstant volym genom hela perioden (6 serier) och det andra benet tränade med variabel volym (6, 3 och 9 serier i träningspass 1-4, 5-8 och 9-12). Muskelbiopsier togs från m. vastus lateralis i träningsgruppen före och 48 timmar efter det första träningspasset. Vidare togs biopsier 48 timmar efter träningspass 4, 5, 8, 9 och 12 samt efter åtta dagar utan träning. Biopsier togs också i kontrollgruppen, före och efter en kontrollperiod på 48 timmar och efter ytterligare 2-4 veckor.

Träningsperioden ledde till muskelhypertrofi och ökade styrka i träningsgruppen. Träning ledde också till ökning av mängden RNA, ribosomalt RNA och ökade proteinnivåer av proteiner relaterade till ribosomal nybildning och struktur (upstream bidning protein, UBF och ribosomalt protein S6, rpS6).
RNA ökade snabbast under de första fyra träningspassen och nådde en platå efter åtta träningspass ($ \ sim $ 50% över utgångsvärden). Variationer i träningsvolymen påverkade inte ökningen av RNA eller ribosomalt RNA.
Nivåer av protein relaterat till ribosomal nybildning (UBF) var korrelerat med totala nivåer av RNA och ökningar av totala RNA-nivåer förutsade i sin tur träningsinducerad muskelhypertrofi. Efter åtta dagar utan träning minskade RNA och specifika ribosomala RNA utan förändringar i muskelmassa. Detta indikerade minskade koncentrationer och nybildning av ribosomer som svar på träningsavbrott. Dessa resultat understryker en avgörande roll för nybildning av ribosomer vid styrketräningsinducerad muskelhypertrofi, och att denna process är känslig för träningsavbrott.

Sammanfattningsvis så visar resultaten i denna avhandling på en avgörande roll för ribosomal nybildning i anpassningar till styrketräning. Vidare så bidrar resultaten till förståelse hur träningsvolymen påverkar anpassningar till styrketräning vad gäller flera aspekter av skelettmuskelns biologi.